"""add hot-column indexes and remaining schema drift

Revision ID: d6f90d12c6ca
Revises: 0002
Create Date: 2026-07-21 13:22:51.508582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'd6f90d12c6ca'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sectors',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('companies',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_impact_score'), ['impact_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source'), ['source'], unique=False)

    with op.batch_alter_table('intelligence_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intelligence_articles_angle'), ['angle'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_articles_parent_event_group_id'), ['parent_event_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_articles_parent_event_group_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_articles_angle'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_source'))
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_events_impact_score'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))
        batch_op.alter_column('companies',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('sectors',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
