import { describe, it, expect } from "vitest";
import { deriveWhatToWatchNext, type WhatToWatchNextInput } from "./whatToWatchNext";

describe("deriveWhatToWatchNext — Homepage Hero 'What To Watch Next' (2026-09-03)", () => {
  // ── 1. Valid deterministic conditions render ────────────────────────────
  it("derives a real observable condition per available real signal", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false },
      crude:     { positive: false },
      usdInr:    { positive: false },
    });
    const byEntity = Object.fromEntries(items.map(i => [i.entity, i.detail]));
    expect(byEntity["Bank Nifty"]).toBe("Whether today's weakness recovers");
    expect(byEntity["Brent Crude"]).toBe("Whether today's decline reverses");
    expect(byEntity["USD/INR"]).toBe("Whether rupee strength persists");
  });

  it("flips wording correctly for the positive direction of each signal (top 4 by priority)", () => {
    // 5 real candidates, 4-item cap -- USD/INR (lowest priority) is
    // dropped here by design; checked in isolation in the next test.
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: true },
      usFutures: { positive: true },
      crude:     { positive: true },
      usdInr:    { positive: true },
      fiiDii:    { available: true, fiiNet: 500 },
    });
    const byEntity = Object.fromEntries(items.map(i => [i.entity, i.detail]));
    expect(byEntity["Bank Nifty"]).toBe("Whether today's gains hold");
    expect(byEntity["FII Flows"]).toBe("Whether FII buying persists");
    expect(byEntity["US Futures"]).toBe("Whether today's strength in US futures holds");
    expect(byEntity["Brent Crude"]).toBe("Whether today's rise continues");
  });

  it("flips USD/INR wording correctly in isolation", () => {
    // usdInr.positive === true means USD/INR rose == rupee weakened.
    const positive = deriveWhatToWatchNext({ usdInr: { positive: true } });
    const negative = deriveWhatToWatchNext({ usdInr: { positive: false } });
    expect(positive[0].detail).toBe("Whether rupee weakness persists");
    expect(negative[0].detail).toBe("Whether rupee strength persists");
  });

  it("every generated phrase describes an observable condition, never a forecast/instruction", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false }, usFutures: { positive: false }, crude: { positive: true },
      usdInr: { positive: true }, fiiDii: { available: true, fiiNet: -100 },
    });
    for (const item of items) {
      expect(item.detail.toLowerCase()).toMatch(/^whether\b/);
      expect(item.detail).not.toMatch(/\bwill\b/i);
      expect(item.detail).not.toMatch(/\btarget\b/i);
      expect(item.detail).not.toMatch(/\bbullish\b|\bbearish\b/i);
    }
  });

  // ── 2. Maximum 4 items ───────────────────────────────────────────────────
  it("never returns more than 4 items even when every signal + 2 triggers are available", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false }, nifty50: { positive: false }, usFutures: { positive: false },
      crude: { positive: false }, usdInr: { positive: false }, fiiDii: { available: true, fiiNet: -1 },
      calendarTriggers: [
        { title: "RBI liquidity data", when: "2:30 PM" },
        { title: "TCS earnings", when: "After Market" },
      ],
    });
    expect(items.length).toBeLessThanOrEqual(4);
  });

  // ── 3. Duplicates removed ────────────────────────────────────────────────
  it("de-duplicates by entity, case-insensitively, keeping the first occurrence", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false },
      calendarTriggers: [{ title: "bank nifty", when: "3:00 PM" }],
    });
    const entities = items.map(i => i.entity.toLowerCase());
    expect(new Set(entities).size).toBe(entities.length);
  });

  it("bankNifty and nifty50 never both appear — one index item at most", () => {
    const items = deriveWhatToWatchNext({ bankNifty: { positive: false }, nifty50: { positive: true } });
    const indexItems = items.filter(i => i.entity === "Bank Nifty" || i.entity === "Nifty 50");
    expect(indexItems.length).toBe(1);
    expect(indexItems[0].entity).toBe("Bank Nifty"); // Bank Nifty preferred when both are present
  });

  // ── 4. Recommendation language is never generated by the deterministic mapper ──
  it("no condition text generated by any real input combination ever trips containsRecommendationLanguage", async () => {
    const { containsRecommendationLanguage } = await import("./recommendationLanguage");
    const bools = [true, false, null] as const;
    for (const bn of bools) for (const uf of bools) for (const cr of bools) for (const ui of bools) {
      const items = deriveWhatToWatchNext({
        bankNifty: { positive: bn }, usFutures: { positive: uf }, crude: { positive: cr }, usdInr: { positive: ui },
        fiiDii: { available: true, fiiNet: 1 },
      });
      for (const item of items) {
        expect(containsRecommendationLanguage(item.detail)).toBe(false);
        expect(containsRecommendationLanguage(item.entity)).toBe(false);
      }
    }
  });

  it("a poisoned calendar trigger title is dropped, not rendered", () => {
    const items = deriveWhatToWatchNext({
      calendarTriggers: [{ title: "Buy HDFC Bank now", when: "3:00 PM" }],
    });
    expect(items.find(i => i.entity === "Buy HDFC Bank now")).toBeUndefined();
  });

  // ── 5. Missing data does not create fabricated fallback items ──────────
  it("returns an empty array when nothing is available, never a placeholder item", () => {
    const items = deriveWhatToWatchNext({});
    expect(items).toEqual([]);
  });

  it("a null signal is simply skipped, not defaulted to some assumed direction", () => {
    const items = deriveWhatToWatchNext({ bankNifty: null, crude: null, usdInr: { positive: false } });
    expect(items.length).toBe(1);
    expect(items[0].entity).toBe("USD/INR");
  });

  // ── 6. Legacy article what_to_watch_next is NOT used as an automatic source ──
  it("the input type has no field for legacy AIPE what_to_watch_next content", () => {
    // Type-level guarantee: WhatToWatchNextInput simply has no such key, so
    // passing one has zero effect even if a caller mistakenly attaches it.
    const withLegacyField = {
      bankNifty: { positive: false },
      what_to_watch_next: ["Buy HDFC Bank now", "Accumulate on dips"],
    } as WhatToWatchNextInput & { what_to_watch_next: string[] };
    const items = deriveWhatToWatchNext(withLegacyField);
    expect(items.every(i => !i.detail.includes("Buy") && !i.detail.includes("Accumulate"))).toBe(true);
    expect(items.length).toBe(1);
    expect(items[0].entity).toBe("Bank Nifty");
  });

  // ── 7. Verified upcoming trigger can render when real data exists ──────
  it("a real calendar trigger renders as a trigger item, ranked first", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false },
      calendarTriggers: [{ title: "RBI liquidity data", when: "2:30 PM", category: "monetary_policy" }],
    });
    expect(items[0]).toMatchObject({ kind: "trigger", entity: "RBI liquidity data", detail: "2:30 PM" });
  });

  it("never invents a trigger — an empty calendarTriggers array produces zero trigger items", () => {
    const items = deriveWhatToWatchNext({ bankNifty: { positive: false }, calendarTriggers: [] });
    expect(items.some(i => i.kind === "trigger")).toBe(false);
  });

  // ── 8. Unknown/unavailable direction does not create a directional condition ──
  it("positive: null/undefined never produces an item for that signal", () => {
    const items1 = deriveWhatToWatchNext({ bankNifty: { positive: null } });
    const items2 = deriveWhatToWatchNext({ bankNifty: { positive: undefined as unknown as null } });
    expect(items1).toEqual([]);
    expect(items2).toEqual([]);
  });

  it("fiiDii.available=false or fiiNet=null never produces an FII item", () => {
    expect(deriveWhatToWatchNext({ fiiDii: { available: false, fiiNet: 100 } })).toEqual([]);
    expect(deriveWhatToWatchNext({ fiiDii: { available: true, fiiNet: null } })).toEqual([]);
  });

  // ── Ranking / priority order ─────────────────────────────────────────────
  it("ranks a verified trigger above every deterministic condition", () => {
    const items = deriveWhatToWatchNext({
      bankNifty: { positive: false }, usFutures: { positive: false }, crude: { positive: false },
      calendarTriggers: [{ title: "US jobs report", when: "Tonight" }],
    });
    expect(items[0].kind).toBe("trigger");
  });

  it("ranks index movement above US Futures/Crude/USD-INR/FII among conditions", () => {
    const items = deriveWhatToWatchNext({
      usdInr: { positive: false }, crude: { positive: false }, usFutures: { positive: false },
      fiiDii: { available: true, fiiNet: -1 }, bankNifty: { positive: false },
    });
    expect(items[0].entity).toBe("Bank Nifty");
  });
});
