"""
Comparison research pages (SEO Phase 2, §2.2) — permanent, indexable
/research/{slug} pages generated from a real AI Search comparison run.

Phase 6G Slice 2 — migrated from ai_search_service.run_ai_search (V2) to
ai_search.pipeline.run_ai_search_v3. Caller migration ONLY: this module's
own downstream logic (compose_what_happened/compose_why_it_matters/
_build_companies_affected/compose_key_takeaway, all below) is untouched
— V3's comparison specialist produces the exact same decision_intelligence
shape this module already consumed (holding_analysis/target_analysis/
comparison[]/tradeoff/decision_framework), confirmed a strict superset
(V3 adds winner/best_investor_type/engine_recommendation on top, removes
nothing). If publish quality changes after this, it's attributable to
the pipeline switch alone, not a simultaneous rewrite.

The quality gate this module adds on top of whichever pipeline it calls
remains exactly as important either way: V2's own documented failure
rate (~47% synthesis-incomplete on comparison-shaped queries, per the
original V3 planning benchmark) means a naive "generate once, publish
unconditionally" approach would regularly publish hollow pages.
generate_comparison() retries a bounded number of times and ONLY returns
a result when the answer is genuinely complete (real decision_intelligence,
not the templated "didn't complete" fallback) — callers must treat None
as "skip this pair," never force-publish a degraded run.
"""
from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings

_MAX_ATTEMPTS = 3


def _truncate_at_word(text: str, limit: int) -> str:
    """Clip to `limit` chars on a word boundary — a raw text[:limit] slice
    regularly lands mid-word or leaves a dangling comma/semicolon in the
    Google SERP snippet, which is exactly the kind of thing that hurts
    click-through on an otherwise well-optimized meta description."""
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(" ,.;:—-") + "…"


def _slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s


# Comparison articles never had a "what happened" — there's no single
# triggering event for an evergreen comparison, so this was left null, and
# the frontend correctly hides the empty section rather than rendering
# broken. Confirmed live as a real gap though (SEO audit's "empty body
# section" finding on itc-vs-hindunilvr): composed here from real
# already-generated fields on the SAME run_ai_search result (holding/target
# theses, real comparison dimensions), same honest-composition pattern as
# the homepage's todaysSummary — never a new LLM call, never an invented
# claim. Extracted as standalone functions (not inlined in
# publish_comparison_article) so a one-off repair job can backfill already-
# published rows from their own already-stored market_context.decision_
# intelligence without needing a fresh LLM call either.
def _sentence(text: str) -> str:
    """Real generated text sometimes already ends in its own period —
    appending another via join produces a visible ".." Strip and re-add
    once so composed paragraphs read as normal sentences regardless."""
    return text.rstrip(".") + "."


def compose_what_happened(di: dict, name_a: str, name_b: str) -> str | None:
    holding_analysis = di.get("holding_analysis") or {}
    target_analysis = di.get("target_analysis") or {}
    dimensions = [c.get("dimension") for c in (di.get("comparison") or []) if c.get("dimension")]
    parts = []
    if dimensions:
        parts.append(f"This comparison evaluates {name_a} against {name_b} across {len(dimensions)} dimensions: {', '.join(dimensions)}.")
    if holding_analysis.get("thesis"):
        parts.append(f"{name_a}: {_sentence(holding_analysis['thesis'])}")
    if target_analysis.get("thesis"):
        parts.append(f"{name_b}: {_sentence(target_analysis['thesis'])}")
    return " ".join(parts) or None


# Same gap, same fix approach, for why_it_matters — real tradeoff data
# already generated by the same run_ai_search result, just never wired into
# the article model. is_evergreen articles were the ones the SEO audit
# found this field hijacked by an unrelated daily-pulse injector on (see
# continuous_updater.py's fix) — giving comparisons a real why_it_matters
# closes the other half of that same finding.
def compose_why_it_matters(di: dict, name_a: str, name_b: str) -> str | None:
    tradeoff = di.get("tradeoff") or {}
    ai_stance = (di.get("decision_framework") or {}).get("ai_stance")
    parts = []
    if tradeoff.get("reasons_to_hold"):
        joined = "; ".join(r.rstrip(".") for r in tradeoff["reasons_to_hold"][:2])
        parts.append(f"In favor of {name_a}: {joined}.")
    if tradeoff.get("reasons_to_switch"):
        joined = "; ".join(r.rstrip(".") for r in tradeoff["reasons_to_switch"][:2])
        parts.append(f"In favor of {name_b}: {joined}.")
    if ai_stance:
        parts.append(f"Overall stance: {_sentence(ai_stance)}")
    return " ".join(parts) or None


# companies_affected used to hardcode impact="neutral" and
# reason="Comparison subject" for BOTH companies on every comparison
# article, regardless of what the run actually concluded — confirmed live
# on acc-vs-ultracemco: 5 of 6 real comparison dimensions favored
# UltraTech, and holding_analysis/target_analysis already carry a real,
# specific thesis per company, but neither ever reached the article. This
# derives both fields from that same already-generated data instead —
# never a new LLM call, never an invented claim, same "real data, don't
# fabricate" rule the rest of this module follows.
def _build_companies_affected(di: dict, name_a: str, symbol_a: str, name_b: str, symbol_b: str) -> list[dict]:
    holding_analysis = di.get("holding_analysis") or {}
    target_analysis = di.get("target_analysis") or {}
    comparison = di.get("comparison") or []

    holding_wins = sum(1 for c in comparison if c.get("advantage") == "holding")
    target_wins = sum(1 for c in comparison if c.get("advantage") == "target")

    # A real, code-computed lean from the same dimension-by-dimension table
    # already shown on the page — not a fabricated score. Only calls it
    # for one side when the lean is clear (a 1-dimension edge on a 6-
    # dimension comparison isn't a real signal); a close/tied comparison
    # honestly stays neutral for both rather than forcing a winner.
    impact_a, impact_b = "neutral", "neutral"
    if holding_wins > target_wins and holding_wins - target_wins >= 2:
        impact_a, impact_b = "positive", "negative"
    elif target_wins > holding_wins and target_wins - holding_wins >= 2:
        impact_a, impact_b = "negative", "positive"

    reason_a = holding_analysis.get("thesis") or "Comparison subject"
    reason_b = target_analysis.get("thesis") or "Comparison subject"

    return [
        {"name": name_a, "symbol": symbol_a, "impact": impact_a, "reason": reason_a},
        {"name": name_b, "symbol": symbol_b, "impact": impact_b, "reason": reason_b},
    ]


# Was ai_stance alone ("Neutral"/"Bullish"/...) — a bare one-word label
# with no context, confirmed live rendering as the entire "30-Second
# Answer" on the article page. decision_summary is the real synthesized
# comparison sentence already generated on the same run; leading with the
# stance word (when present) keeps the quick-scan verdict while the
# sentence gives it substance. Extracted as its own function (same reason
# as compose_what_happened/_build_companies_affected) so the backfill
# endpoint can recompute it from an already-published article's own stored
# market_context without a fresh AI Search call.
def compose_key_takeaway(di: dict, decision_summary: str) -> str:
    ai_stance = (di.get("decision_framework") or {}).get("ai_stance")
    if ai_stance and decision_summary:
        return f"{ai_stance}. {decision_summary}"
    return decision_summary or ai_stance or ""


async def _try_generate(query: str, db: AsyncSession) -> dict | None:
    from app.services.ai_search.pipeline import run_ai_search_v3
    from app.services.aipe.recommendation_language import scan_recommendation_language

    try:
        result, _was_cached = await run_ai_search_v3(query, db)
    except Exception:
        return None
    if not result or result.get("synthesis_incomplete"):
        return None
    di = result.get("decision_intelligence") or {}
    # A genuinely complete comparison has real per-entity analysis, not
    # just intent detection + the deterministic engine_recommendation
    # block (present even on a degraded run).
    if not di.get("holding_analysis") and not di.get("comparison"):
        return None

    # Directional-surface reassessment (2026-09-03) — comparison_publisher.py
    # never wired the recommendation-language validator at all, confirmed
    # live: a real /research/{slug} page's key_takeaway read "Favor GAIL
    # India Ltd for 12-month capital appreciation... preferred choice over
    # Oil & Natural Gas Corporation," matching none of the existing
    # patterns (now extended, see recommendation_language.py). Same
    # treatment as synthesis_incomplete above -- a run whose real would-be
    # key_takeaway trips the same required, publish-blocking check every
    # other AIPE article type already enforces is not "genuinely
    # complete," it's unsafe -- retry (generate_comparison's existing
    # bounded loop), never publish. di is the exact object market_context
    # would also store, so rejecting here also keeps the unsafe
    # decision_framework.ai_stance out of the frontend's raw market_context
    # render, not just out of key_takeaway.
    decision_summary = di.get("decision_summary") or (result.get("answer") or {}).get("bottom_line") or ""
    would_be_key_takeaway = compose_key_takeaway(di, decision_summary)
    if scan_recommendation_language({"key_takeaway": would_be_key_takeaway}):
        return None

    return result


async def generate_comparison(
    db: AsyncSession, symbol_a: str, symbol_b: str, name_a: str, name_b: str,
) -> dict | None:
    """Real comparison content or None — never a partial/degraded publish.
    Tries up to _MAX_ATTEMPTS times since V2's free-tier provider chain is
    genuinely flaky run-to-run for the same query (confirmed live: the
    exact same query succeeded on one attempt and hit the templated
    fallback on another)."""
    query = f"{name_a} vs {name_b}, which is better for 12 months?"
    for _ in range(_MAX_ATTEMPTS):
        result = await _try_generate(query, db)
        if result:
            return result
    return None


async def publish_comparison_article(
    db: AsyncSession, symbol_a: str, symbol_b: str, name_a: str, name_b: str, sector: str | None = None,
) -> dict | None:
    """Generates (with retry+quality-gate) and stores a comparison as a
    permanent IntelligenceArticle row. Returns the stored row's public
    fields, or None if no attempt produced real content — the caller
    (a seed script or an on-demand admin trigger) must treat None as
    "nothing published," not retry-forever or fabricate a stand-in."""
    from app.db.models.intelligence_article import IntelligenceArticle
    from sqlalchemy import select

    result = await generate_comparison(db, symbol_a, symbol_b, name_a, name_b)
    if not result:
        return None

    di = result.get("decision_intelligence") or {}
    verdict = result.get("investment_verdict") or {}
    ai_answer = result.get("answer") or {}

    slug = f"{_slugify(symbol_a)}-vs-{_slugify(symbol_b)}"
    site_url = (settings.frontend_url or "https://www.marketripple.in").rstrip("/")
    canonical_url = f"{site_url}/research/{slug}"

    headline = f"{name_a} vs {name_b}: Which Is The Better Investment?"
    decision_summary = di.get("decision_summary") or ai_answer.get("bottom_line") or ""
    meta_description = _truncate_at_word(
        decision_summary or f"AI-powered comparison of {name_a} and {name_b} — valuation, growth drivers, risks, and a research-framed verdict on MarketRipple.",
        160,
    )
    key_takeaway = compose_key_takeaway(di, decision_summary)

    what_happened = compose_what_happened(di, name_a, name_b)
    why_it_matters = compose_why_it_matters(di, name_a, name_b)

    now = datetime.now(timezone.utc)
    existing_lookup = (await db.execute(
        select(IntelligenceArticle).where(IntelligenceArticle.slug == slug)
    )).scalar_one_or_none()
    # datePublished must stay fixed at the article's real first-publish time —
    # this refresh cycle runs every 14 days (comparison_scheduler.py), and
    # rebuilding json_ld from scratch here was previously resetting
    # datePublished to "now" on every single refresh, which is actively wrong
    # (not just stale) for an Article's structured-data freshness signal.
    date_published = (existing_lookup.published_at or now) if existing_lookup else now
    json_ld = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": headline,
        "description": meta_description,
        "datePublished": date_published.isoformat(),
        "dateModified": now.isoformat(),
        "author": {"@type": "Organization", "name": "MarketRipple AI Intelligence Engine"},
        "publisher": {"@type": "Organization", "name": "MarketRipple"},
        "mainEntityOfPage": canonical_url,
        "breadcrumb": {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "MarketRipple", "item": site_url},
                {"@type": "ListItem", "position": 2, "name": "Research", "item": f"{site_url}/research"},
                {"@type": "ListItem", "position": 3, "name": headline, "item": canonical_url},
            ],
        },
    }

    companies_affected = _build_companies_affected(di, name_a, symbol_a, name_b, symbol_b)
    sectors_affected = [{"name": sector, "impact": "neutral", "magnitude": "medium"}] if sector else []

    # market_context is the generic free-form JSON field on this model —
    # stashes the full comparison structure (holding/target analysis,
    # dimension-by-dimension table, tradeoff, decision_framework) without
    # a schema migration, same reasoning as market_context's existing use
    # elsewhere in the AIPE pipeline for "real structured context that
    # doesn't fit the fixed columns."
    market_context = {
        "kind": "comparison",
        "decision_intelligence": di,
        "investment_verdict": verdict,
    }

    existing = existing_lookup

    if existing:
        existing.headline = headline
        existing.executive_summary = decision_summary
        existing.key_takeaway = key_takeaway
        existing.what_happened = what_happened
        existing.why_it_matters = why_it_matters
        existing.companies_affected = companies_affected
        existing.sectors_affected = sectors_affected
        existing.seo_title = headline
        existing.meta_description = meta_description
        existing.canonical_url = canonical_url
        existing.json_ld = json_ld
        existing.market_context = market_context
        existing.last_updated = now
        existing.update_count = (existing.update_count or 0) + 1
        article = existing
    else:
        article = IntelligenceArticle(
            id=str(uuid.uuid4()), slug=slug, article_type="comparison_intelligence",
            angle="comparison", is_evergreen=True,
            lifecycle_status="published", status="published",
            headline=headline, executive_summary=decision_summary,
            key_takeaway=key_takeaway,
            what_happened=what_happened,
            why_it_matters=why_it_matters,
            companies_affected=companies_affected, sectors_affected=sectors_affected,
            sources=["MarketRipple AI Search Engine"],
            seo_title=headline, meta_description=meta_description,
            canonical_url=canonical_url, json_ld=json_ld, market_context=market_context,
            confidence_score=float(verdict.get("confidence", 50) or 50) / 100,
            published_at=now, last_updated=now,
        )
        db.add(article)

    await db.commit()
    return {"slug": slug, "headline": headline}
